source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.7.5"

gem "rails", "~> 7.0.10"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "bootsnap", require: false

# Bundled explicitly so `bundle install --path vendor/bundle` works on Ruby 2.7
gem "date", "~> 3.5"
gem "timeout", "~> 0.6"

gem "bcrypt", "~> 3.1.7"
gem "jwt"
gem "pundit"
gem "rack-cors"

gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

group :development, :test do
  gem "rspec-rails", "~> 6.0"
  gem "factory_bot_rails"
  gem "faker"
end

group :development do
end
